# Inhoud per dienstpagina. Sleutel = nieuwe slug.
# h1 = (vast deel, verloopdeel). kw = primair zoekwoord (title, H1, eerste alinea).
# Geen prijzen, geen verzonnen cijfers.

D = {
"seo-specialist-inhuren": dict(
    short="SEO", noun="SEO-specialist", h1=("SEO-specialist", "inhuren"),
    title="SEO-specialist inhuren: SEO-student | Marketing Student",
    meta="SEO-specialist inhuren zonder bureautarief. Een getrainde SEO-student, begeleid door een senior. Geen contract. Vraag een offerte aan.",
    lead="Een SEO-specialist inhuren voor je website: een getrainde SEO-student doet zoekwoordonderzoek, verbetert je pagina's en schrijft content die rankt. Een senior SEO-specialist controleert het werk.",
    mentor="Jeroen B.", sc="seo", platforms="seo",
    tasks=[("search","Zoekwoordonderzoek","Welke zoekwoorden leveren klanten op? De student brengt ze in kaart per pagina."),
           ("code","Technische SEO-check","Snelheid, indexering en fouten. Met Screaming Frog, SE Ranking en Ahrefs."),
           ("pen","On-page optimalisatie","Titels, meta, koppen en interne links op elke belangrijke pagina."),
           ("file","Content die rankt","Dienstpagina's en blogs, geschreven op zoekintentie en gecontroleerd door een senior."),
           ("link","Autoriteit en links","Relevante vermeldingen en links, altijd whitehat."),
           ("bar-chart","Rapportage","Elke maand posities, klikken en volgende stappen, uit Search Console.")],
    faq=[("Wat doet een SEO-specialist?","Een SEO-specialist zorgt dat je website hoger in Google komt. Onze SEO-student doet zoekwoordonderzoek, verbetert techniek en pagina's en schrijft content. Een senior SEO-specialist controleert het werk."),
         ("Wat kost een SEO-specialist inhuren?",""),("Wat is het verschil met een SEO-freelancer?",""),
         ("Hoe snel zie ik resultaat van SEO?",""),("Welke tools gebruikt de student?",""),("Zit ik vast aan een contract?","")],
    blog=[("SEO","Wat doet een SEO-specialist?","De taken, tools en resultaten die je mag verwachten."),
          ("SEO","SEO uitbesteden of zelf doen?","Wat je zelf kunt en wanneer een specialist loont."),
          ("SEO","Hoe lang duurt het voordat SEO werkt?","Wat je na vier weken, drie maanden en een half jaar ziet.")],
    cta="Huur een SEO-specialist in"),

"google-ads-specialist-inhuren": dict(
    short="Google Ads", noun="Google Ads-specialist", h1=("Google Ads-specialist", "inhuren"),
    title="Google Ads-specialist inhuren | Marketing Student",
    meta="Google Ads-specialist inhuren: een getrainde SEA-student zet je campagnes op en stuurt bij, begeleid door een senior. Geen contract.",
    lead="Een Google Ads-specialist inhuren die elke week je campagnes bijstuurt: een getrainde SEA-student, begeleid door een senior SEA-specialist. Jij houdt je eigen account en al je data.",
    mentor="Jeroen B.", sc="ads", platforms="ads",
    tasks=[("search","Zoekwoorden en structuur","Campagnes en advertentiegroepen die aansluiten op wat je klant zoekt."),
           ("pen","Advertentieteksten","Responsieve advertenties, getest en verbeterd op basis van resultaat."),
           ("target","Biedstrategie","Budget en biedingen afgestemd op je doel: leads, verkopen of bereik."),
           ("cart","Shopping en Performance Max","Productfeed en campagnes voor webshops."),
           ("check-circle","Conversiemeting","Controle van je conversies, zodat je stuurt op echte resultaten."),
           ("bar-chart","Rapportage","Elke maand kosten, conversies en volgende stappen.")],
    faq=[("Wat doet een Google Ads-specialist?","Een Google Ads-specialist zet je advertenties in Google op, bewaakt het budget en verbetert de campagnes op basis van resultaat. Onze SEA-student doet dat werk, een senior SEA-specialist controleert het."),
         ("Wat kost een Google Ads-specialist inhuren?",""),("Wat is het verschil met een Google Ads-freelancer?",""),
         ("Werkt de student in mijn eigen account?",""),("Hoe snel kan de student starten?",""),("Zit ik vast aan een contract?","")],
    blog=[("SEA","Google Ads uitbesteden of zelf doen?","Wanneer een specialist het verschil maakt."),
          ("SEA","Zo lees je je Google Ads-rapport","De cijfers die ertoe doen, en welke je mag negeren."),
          ("SEA","SEO of Google Ads: waar begin je?","Het verschil in snelheid, kosten en effect.")],
    cta="Huur een Google Ads-specialist in"),

"social-media-uitbesteden": dict(
    short="Social media", noun="social media-student", h1=("Social media", "uitbesteden"),
    title="Social media uitbesteden aan een student | Marketing Student",
    meta="Social media uitbesteden aan een getrainde student: posts plannen, maken en beheren, begeleid door een senior. Geen contract.",
    lead="Social media uitbesteden aan een getrainde student: posts bedenken, maken, plannen en je community beheren. Een senior content- en brandingspecialist bewaakt je toon en merk.",
    mentor="Marije C.", sc="social", platforms="social",
    tasks=[("calendar","Contentkalender","Een planning per maand, afgestemd op je doelen en je doelgroep."),
           ("camera","Posts en reels maken","Foto, video en tekst in de stijl van jouw merk."),
           ("share","Plannen en posten","Op het juiste moment, op de kanalen die voor jou werken."),
           ("users","Community beheren","Reacties en berichten beantwoorden, in jouw toon."),
           ("target","Social ads","Advertenties op Meta, LinkedIn en TikTok, als je dat wilt."),
           ("bar-chart","Rapportage","Elke maand bereik, interactie en wat we volgende maand anders doen.")],
    faq=[("Wat doet een social media-student?","Een social media-student bedenkt, maakt en plant je posts en beheert je community. Een senior content- en brandingspecialist controleert of alles past bij je merk."),
         ("Wat kost social media uitbesteden?",""),("Wat is het verschil met een social media-freelancer?",""),
         ("Welke kanalen neemt de student mee?",""),("Houd ik zelf de regie over wat er gepost wordt?",""),("Zit ik vast aan een contract?","")],
    blog=[("Social media","Welke social media is het populairst in Nederland?","Welke kanalen je doelgroep gebruikt, en waar je dus moet zijn."),
          ("Social media","Social media uitbesteden: waar let je op?","Zo kies je de juiste hulp en houd je de regie."),
          ("Social media","Hoe vaak moet je posten?","Een haalbaar ritme per kanaal.")],
    cta="Besteed je social media uit"),

"ai-specialist-inhuren": dict(
    short="AI", noun="AI-specialist", h1=("AI-specialist", "inhuren"),
    title="AI-specialist inhuren voor je marketing | Marketing Student",
    meta="AI-specialist inhuren voor je marketing: een getrainde student zet AI-tools en workflows op, begeleid door een senior. Geen contract.",
    lead="Een AI-specialist inhuren voor je marketing: een getrainde student zet AI-tools en workflows op die je team tijd besparen. Een senior marketeer bewaakt kwaliteit en privacy.",
    mentor=None, sc=None, platforms="ai",
    tasks=[("search","Kansen in kaart","Welke taken in je marketing kunnen sneller of beter met AI?"),
           ("bot","Workflows bouwen","Van briefing tot eerste versie, met tools als ChatGPT en Claude."),
           ("pen","Content met AI","Teksten en ideeën, altijd gecontroleerd door een mens."),
           ("layers","Koppelingen","AI verbinden met de tools die je al gebruikt."),
           ("users","Je team trainen","Zodat je collega's de workflows zelf kunnen gebruiken."),
           ("shield","Privacy en kwaliteit","Duidelijke afspraken over data en controle.")],
    faq=[("Wat doet een AI-specialist?","Een AI-specialist zoekt uit waar AI je marketing sneller of beter maakt en zet die workflows op. Onze student doet het werk, een senior marketeer controleert kwaliteit en privacy."),
         ("Wat kost een AI-specialist inhuren?",""),("Met welke AI-tools werkt de student?",""),
         ("Hoe zit het met privacy en mijn data?",""),("Zit ik vast aan een contract?","")],
    blog=[("AI","Wat doet een AI-specialist in marketing?","De taken die je vandaag al kunt uitbesteden."),
          ("AI","AI in je marketing: waar begin je?","Drie workflows die snel tijd besparen."),
          ("AI","Vindbaar in ChatGPT en Google AI","Wat er verandert voor je vindbaarheid.")],
    cta="Huur een AI-specialist in"),

"claude-specialist-inhuren": dict(
    short="Claude", noun="Claude-specialist", h1=("Claude-specialist", "inhuren"),
    title="Claude-specialist inhuren | Marketing Student",
    meta="Claude-specialist inhuren: een getrainde student zet Claude in voor je content en processen, begeleid door een senior. Geen contract.",
    lead="Een Claude-specialist inhuren: een getrainde student zet Claude in voor je content, klantvragen en interne processen. Een senior marketeer bewaakt kwaliteit en privacy.",
    mentor=None, sc=None, platforms=None,
    tasks=[("search","Toepassingen kiezen","Waar levert Claude jouw team de meeste tijd op?"),
           ("bot","Projecten en prompts","Vaste instructies en kennis, zodat de output past bij je merk."),
           ("pen","Content en documenten","Teksten, samenvattingen en analyses als eerste versie."),
           ("layers","Koppelingen","Claude verbinden met de tools die je al gebruikt."),
           ("users","Je team trainen","Zodat iedereen Claude goed en veilig gebruikt."),
           ("shield","Privacy en kwaliteit","Afspraken over data en menselijke controle.")],
    faq=[("Wat doet een Claude-specialist?","Een Claude-specialist zet het AI-model Claude in voor jouw content en processen: van vaste instructies tot koppelingen met je tools. Een senior marketeer controleert het resultaat."),
         ("Wat kost een Claude-specialist inhuren?",""),("Wat is het verschil tussen Claude en ChatGPT?",""),
         ("Hoe zit het met privacy en mijn data?",""),("Zit ik vast aan een contract?","")],
    blog=[("AI","Wat kun je met Claude in je marketing?","Toepassingen voor content, analyse en klantcontact."),
          ("AI","Claude of ChatGPT: welke past bij jou?","De verschillen voor marketingteams."),
          ("AI","Zo schrijf je een goede prompt","Vijf regels voor betere output.")],
    cta="Huur een Claude-specialist in"),

"contentmarketing-uitbesteden": dict(
    short="Content", noun="content creator", h1=("Contentmarketing", "uitbesteden"),
    title="Contentmarketing uitbesteden | Marketing Student",
    meta="Contentmarketing uitbesteden: een getrainde content creator maakt foto, video en tekst voor je kanalen, begeleid door een senior.",
    lead="Contentmarketing uitbesteden aan een getrainde content creator: foto, video en tekst voor je website en social media. Een senior content- en brandingspecialist bewaakt je merk.",
    mentor="Marije C.", sc="content", platforms="content",
    tasks=[("calendar","Contentplan","Onderwerpen en formats die passen bij je doelgroep."),
           ("camera","Foto en video","Opnames op locatie of met je eigen materiaal."),
           ("play","Reels en korte video","Gemonteerd voor Instagram, TikTok en YouTube Shorts."),
           ("pen","Teksten","Blogs, captions en webteksten in jouw toon."),
           ("layers","Hergebruik","Eén opname omgezet naar content voor meerdere kanalen."),
           ("bar-chart","Evaluatie","Wat werkte, en wat maken we volgende maand.")],
    faq=[("Wat doet een content creator?","Een content creator bedenkt en maakt foto's, video's en teksten voor je kanalen. Onze student doet dat in jouw stijl, een senior content- en brandingspecialist controleert het."),
         ("Wat kost contentmarketing uitbesteden?",""),("Komt de student op locatie filmen?",""),
         ("Wie is eigenaar van de content?",""),("Zit ik vast aan een contract?","")],
    blog=[("Content","Contentmarketing uitbesteden: zo pak je het aan","Van briefing tot planning."),
          ("Content","Welke content werkt voor het mkb?","Formats die weinig tijd kosten en veel opleveren."),
          ("Content","Eén opname, tien stukken content","Zo haal je meer uit elke draaidag.")],
    cta="Besteed je contentmarketing uit"),

"huisstijl-laten-maken": dict(
    short="Branding", noun="brandingstudent", h1=("Huisstijl", "laten maken"),
    title="Huisstijl laten maken door een student | Marketing Student",
    meta="Huisstijl laten maken: een getrainde brandingstudent ontwerpt logo, kleuren en tone of voice, begeleid door een senior brandingspecialist.",
    lead="Een huisstijl laten maken door een getrainde brandingstudent: logo, kleuren, typografie en tone of voice. Een senior brandingspecialist begeleidt elke stap.",
    mentor="Marije C.", sc=None, platforms=None,
    tasks=[("search","Merkonderzoek","Wie ben je, voor wie, en wat maakt je anders?"),
           ("pen","Logo en beeldmerk","Ontwerpen in rondes, tot het klopt."),
           ("layers","Kleuren en typografie","Een palet en lettertypen die overal werken."),
           ("file","Tone of voice","Hoe je merk klinkt, vastgelegd met voorbeelden."),
           ("building","Toepassingen","Visitekaartjes, social media-templates en presentaties."),
           ("check-circle","Merkhandboek","Alle afspraken op één plek, voor iedereen die met je merk werkt.")],
    faq=[("Wat hoort er bij een huisstijl?","Een huisstijl bestaat uit je logo, kleuren, lettertypen, beeldtaal en tone of voice. Samen zorgen ze dat je merk overal herkenbaar is. Onze student maakt ze, een senior brandingspecialist begeleidt het proces."),
         ("Wat kost een huisstijl laten maken?",""),("Hoeveel ontwerprondes krijg ik?",""),
         ("Krijg ik alle bestanden?",""),("Kan de student ook mijn bestaande huisstijl vernieuwen?","")],
    blog=[("Branding","Wat hoort er bij een huisstijl?","De onderdelen op een rij, met voorbeelden."),
          ("Branding","Zo schrijf je een goede ontwerpbriefing","Wat een ontwerper van je moet weten."),
          ("Branding","Branding uitbesteden: waar let je op?","Zo kies je de juiste hulp.")],
    cta="Laat je huisstijl maken"),

"email-marketing-uitbesteden": dict(
    short="E-mailmarketing", noun="e-mailmarketeer", h1=("E-mailmarketing", "uitbesteden"),
    title="Email marketing uitbesteden | Marketing Student",
    meta="E-mailmarketing uitbesteden: nieuwsbrieven en automatische flows door een getrainde student, begeleid door een senior. Geen contract.",
    lead="E-mailmarketing uitbesteden aan een getrainde student: nieuwsbrieven, automatische flows en segmentatie. Een senior marketeer controleert elke verzending.",
    mentor="Marije C.", sc=None, platforms=None,
    tasks=[("mail","Nieuwsbrieven","Opzet, tekst en ontwerp, in jouw huisstijl."),
           ("refresh","Automatische flows","Welkom, verlaten winkelwagen, heractivatie."),
           ("users","Segmentatie","De juiste mail naar de juiste groep."),
           ("pen","Onderwerpregels testen","A/B-testen om je openingen te verbeteren."),
           ("shield","Privacy en AVG","Toestemming en afmelden goed geregeld."),
           ("bar-chart","Rapportage","Openingen, kliks en omzet per mail.")],
    faq=[("Wat doet een e-mailmarketeer?","Een e-mailmarketeer maakt nieuwsbrieven en automatische mails die klanten terug laten komen. Onze student bouwt ze in jouw mailtool, een senior marketeer controleert elke verzending."),
         ("Wat kost email marketing uitbesteden?",""),("In welke mailtools werkt de student?",""),
         ("Kan de student ook mijn nieuwsbrief schrijven?",""),("Zit ik vast aan een contract?","")],
    blog=[("E-mail","Nieuwsbrief uitbesteden: zo pak je het aan","Van eerste mail tot vast ritme."),
          ("E-mail","Vijf automatische mails die elke webshop nodig heeft","Flows die zonder omkijken werken."),
          ("E-mail","Zo schrijf je een onderwerpregel die geopend wordt","Praktische regels en voorbeelden.")],
    cta="Besteed je e-mailmarketing uit"),

"wordpress-specialist-inhuren": dict(
    short="WordPress", noun="WordPress-specialist", h1=("WordPress-specialist", "inhuren"),
    title="WordPress-specialist inhuren | Marketing Student",
    meta="WordPress-specialist inhuren: een getrainde student bouwt en onderhoudt je pagina's, begeleid door een senior. Geen contract.",
    lead="Een WordPress-specialist inhuren voor je website: een getrainde student bouwt pagina's, houdt plugins bij en maakt je site sneller. Een senior controleert het werk.",
    mentor=None, sc=None, platforms="wordpress",
    tasks=[("layers","Pagina's bouwen","Nieuwe pagina's in je bestaande thema of pagebuilder."),
           ("refresh","Onderhoud en updates","WordPress, thema en plugins veilig bijgewerkt."),
           ("zap","Snelheid","Afbeeldingen, caching en scripts, voor een snellere site."),
           ("search","SEO-basis","Titels, meta en structuur goed ingericht."),
           ("cart","WooCommerce","Producten en instellingen voor je webshop."),
           ("shield","Back-ups en beveiliging","Zodat je site blijft draaien.")],
    faq=[("Wat doet een WordPress-specialist?","Een WordPress-specialist bouwt en onderhoudt je website: pagina's, plugins, snelheid en beveiliging. Onze student doet het werk, een senior controleert het."),
         ("Wat kost een WordPress-specialist inhuren?",""),("Werkt de student in mijn bestaande thema?",""),
         ("Kan de student ook een nieuwe website bouwen?",""),("Zit ik vast aan een contract?","")],
    blog=[("WordPress","Zo maak je je WordPress-site sneller","De stappen met het meeste effect."),
          ("WordPress","WordPress-onderhoud: wat moet je bijhouden?","Een checklist per maand."),
          ("WordPress","Welke plugins heb je echt nodig?","Een korte lijst voor het mkb.")],
    cta="Huur een WordPress-specialist in"),

"tiktok-uitbesteden": dict(
    short="TikTok", noun="TikTok-student", h1=("TikTok", "uitbesteden"),
    title="TikTok uitbesteden aan een student | Marketing Student",
    meta="TikTok uitbesteden aan een getrainde student: video's bedenken, filmen en posten, begeleid door een senior. Geen contract.",
    lead="TikTok uitbesteden aan een student die het platform kent: video's bedenken, filmen, monteren en posten. Een senior content- en brandingspecialist bewaakt je merk.",
    mentor="Marije C.", sc="tiktok", platforms=None,
    tasks=[("search","Trends en formats","Wat werkt op TikTok, vertaald naar jouw merk."),
           ("camera","Filmen","Op locatie of met materiaal dat je zelf aanlevert."),
           ("play","Monteren","Korte video's met ondertiteling en muziek."),
           ("calendar","Plannen en posten","Een vast ritme, op het juiste moment."),
           ("target","TikTok-advertenties","Als je je bereik wilt vergroten."),
           ("bar-chart","Rapportage","Weergaven, volgers en wat we volgende maand doen.")],
    faq=[("Wat doet een TikTok-student?","Een TikTok-student bedenkt, filmt en monteert video's voor je TikTok-account en post ze op vaste momenten. Een senior content- en brandingspecialist controleert of alles bij je merk past."),
         ("Wat kost TikTok uitbesteden?",""),("Moet ik zelf in beeld?",""),
         ("Past TikTok bij mijn bedrijf?",""),("Zit ik vast aan een contract?","")],
    blog=[("Social media","Past TikTok bij jouw bedrijf?","Zo bepaal je of je doelgroep er zit."),
          ("Social media","TikTok voor bedrijven: zo begin je","Account, eerste video's en ritme."),
          ("Social media","Welke social media is het populairst in Nederland?","Welke kanalen je doelgroep gebruikt.")],
    cta="Besteed je TikTok uit"),

"instagram-uitbesteden": dict(
    short="Instagram", noun="Instagram-student", h1=("Instagram", "uitbesteden"),
    title="Instagram uitbesteden aan een student | Marketing Student",
    meta="Instagram uitbesteden aan een getrainde student: feed, stories en reels, gepland en gemaakt, begeleid door een senior.",
    lead="Instagram uitbesteden aan een getrainde student: je feed, stories en reels bedenken, maken en plannen. Een senior content- en brandingspecialist bewaakt je merk.",
    mentor="Marije C.", sc="instagram", platforms="instagram",
    tasks=[("calendar","Contentplan","Een maandplanning voor feed, stories en reels."),
           ("camera","Foto en reels","Gemaakt in de stijl van jouw merk."),
           ("pen","Captions en hashtags","Teksten die passen bij je toon en doelgroep."),
           ("users","Community beheren","Reacties en DM's beantwoorden."),
           ("target","Instagram-advertenties","Via Meta, als je je bereik wilt vergroten."),
           ("bar-chart","Rapportage","Bereik, interactie en groei per maand.")],
    faq=[("Wat doet een Instagram-student?","Een Instagram-student bedenkt en maakt je posts, stories en reels, plant ze in en beantwoordt reacties. Een senior content- en brandingspecialist controleert het werk."),
         ("Wat kost Instagram uitbesteden?",""),("Kan de student ook mijn Instagram-beheer overnemen?",""),
         ("Houd ik zelf toegang tot mijn account?",""),("Zit ik vast aan een contract?","")],
    blog=[("Social media","Instagram beheer uitbesteden: waar let je op?","Zo houd je de regie."),
          ("Social media","Reels voor bedrijven: zo begin je","Formats die weinig tijd kosten."),
          ("Social media","Welke social media is het populairst in Nederland?","Welke kanalen je doelgroep gebruikt.")],
    cta="Besteed je Instagram uit"),

"linkedin-marketing-uitbesteden": dict(
    short="LinkedIn", noun="LinkedIn-student", h1=("LinkedIn-marketing", "uitbesteden"),
    title="LinkedIn-marketing uitbesteden | Marketing Student",
    meta="LinkedIn-marketing uitbesteden: bedrijfspagina, posts en advertenties door een getrainde student, begeleid door een senior.",
    lead="LinkedIn-marketing uitbesteden aan een getrainde student: je bedrijfspagina, posts en advertenties voor zakelijke klanten. Een senior content- en brandingspecialist bewaakt je toon.",
    mentor="Marije C.", sc="linkedin", platforms=None,
    tasks=[("building","Bedrijfspagina","Volledig ingericht en herkenbaar."),
           ("pen","Posts schrijven","Voor je bedrijfspagina en voor je eigen profiel."),
           ("calendar","Contentplanning","Een vast ritme dat je volhoudt."),
           ("users","Netwerk en interactie","Reageren, verbinden en zichtbaar blijven."),
           ("target","LinkedIn-advertenties","Gericht op functie, branche en bedrijfsgrootte."),
           ("bar-chart","Rapportage","Bereik, volgers en leads per maand.")],
    faq=[("Wat doet een LinkedIn-student?","Een LinkedIn-student schrijft en plant posts voor je bedrijfspagina en profiel en zet eventueel advertenties op. Een senior content- en brandingspecialist controleert de toon."),
         ("Wat kost LinkedIn-marketing uitbesteden?",""),("Kan de student ook voor mijn persoonlijke profiel schrijven?",""),
         ("Levert LinkedIn leads op?",""),("Zit ik vast aan een contract?","")],
    blog=[("Social media","LinkedIn uitbesteden: zo pak je het aan","Van bedrijfspagina tot vast ritme."),
          ("Social media","Zo schrijf je een LinkedIn-post die gelezen wordt","Opbouw en voorbeelden."),
          ("Social media","LinkedIn-advertenties voor het mkb","Wanneer ze lonen.")],
    cta="Besteed je LinkedIn-marketing uit"),

"shopify-specialist-inhuren": dict(
    short="Shopify", noun="Shopify-specialist", h1=("Shopify-specialist", "inhuren"),
    title="Shopify-specialist inhuren | Marketing Student",
    meta="Shopify-specialist inhuren: een getrainde student beheert je webshop, productpagina's en apps, begeleid door een senior.",
    lead="Een Shopify-specialist inhuren voor je webshop: een getrainde student beheert producten, apps en pagina's en verbetert je conversie. Een senior controleert het werk.",
    mentor=None, sc=None, platforms="shopify",
    tasks=[("cart","Productbeheer","Producten, varianten en collecties op orde."),
           ("pen","Productteksten","Teksten die verkopen en vindbaar zijn."),
           ("layers","Thema en pagina's","Aanpassingen in je bestaande thema."),
           ("zap","Apps en koppelingen","De juiste apps, goed ingesteld."),
           ("search","SEO voor je webshop","Titels, meta en structuur voor Google."),
           ("bar-chart","Rapportage","Bezoekers, conversie en omzet per maand.")],
    faq=[("Wat doet een Shopify-specialist?","Een Shopify-specialist beheert en verbetert je webshop: producten, apps, thema en vindbaarheid. Onze student doet het werk, een senior controleert het."),
         ("Wat kost een Shopify-specialist inhuren?",""),("Kan de student een nieuwe Shopify-winkel opzetten?",""),
         ("Werkt de student in mijn bestaande thema?",""),("Zit ik vast aan een contract?","")],
    blog=[("E-commerce","Zo schrijf je een productpagina die verkoopt","Opbouw en voorbeelden."),
          ("E-commerce","SEO voor je Shopify-winkel","De instellingen die ertoe doen."),
          ("E-commerce","Welke Shopify-apps heb je echt nodig?","Een korte lijst voor starters.")],
    cta="Huur een Shopify-specialist in"),
}

# Showcase-collages: (merk, naam, label, soort)
SC = {
    "seo": dict(pill="Voorbeeld van het resultaat", t1="Jouw bedrijf", t2="bovenaan in Google", vraag="installateur amersfoort",
                lead="Wie zoekt, klikt op de eerste resultaten. De student werkt structureel aan de posities van jouw website, in elke vorm waarin Google je toont.",
                sr="Voorbeeld: jouw bedrijf staat bovenaan in Google Zoeken, Google Maps, het uitgelichte fragment, op mobiel, in Bing en in het antwoord van ChatGPT.",
                links=[("google","Google"),("microsoft","Bing"),("openai","ChatGPT"),("perplexity","Perplexity")],
                kaarten=[("google","Google","Zoeken","serp"),("google","Google","Maps","local"),("microsoft","Bing","","serp"),
                         ("google","Google","Mobiel","serp"),("google","Google","Fragment","snippet"),("openai","ChatGPT","","chat")]),
    "ads": dict(pill="Voorbeeld van het resultaat", t1="Jouw advertentie", t2="bovenaan in Google", vraag="cv-ketel vervangen",
                lead="Zodra iemand zoekt, staat jouw advertentie bovenaan. De student beheert de campagnes, de senior bewaakt budget en resultaat.",
                sr="Voorbeeld: de advertentie van jouw bedrijf staat bovenaan in Google Ads, op mobiel, in Microsoft Ads, op YouTube, in Google Maps en op Instagram.",
                links=[("googleads","Google Ads"),("microsoft","Microsoft Ads"),("youtube","YouTube"),("meta","Meta")],
                kaarten=[("googleads","Google Ads","Zoeken","ad"),("googleads","Google Ads","Mobiel","ad"),("microsoft","Microsoft Ads","","ad"),
                         ("google","Google","Maps","local"),("youtube","YouTube","Advertentie","social"),("instagram","Instagram","Gesponsord","social")]),
    "social": dict(pill="Voorbeeld van het resultaat", t1="Jouw merk", t2="zichtbaar op elk kanaal", vraag="nieuwe collectie",
                   lead="Een vast ritme van goede posts, op de kanalen waar je klanten zitten. De student maakt en plant, de senior bewaakt je merk.",
                   sr="Voorbeeld: posts van jouw merk op Instagram, Facebook, LinkedIn, TikTok, YouTube en in Google.",
                   links=[("instagram","Instagram"),("facebook","Facebook"),("linkedin","LinkedIn"),("tiktok","TikTok")],
                   kaarten=[("instagram","Instagram","","social"),("facebook","Facebook","","social"),("linkedin","LinkedIn","","social"),
                            ("tiktok","TikTok","","social"),("youtube","YouTube","Shorts","social"),("google","Google","Zoeken","serp")]),
    "content": dict(pill="Voorbeeld van het resultaat", t1="Jouw content", t2="op elk kanaal", vraag="achter de schermen",
                    lead="Eén opname, content voor al je kanalen. De student maakt en monteert, de senior bewaakt je merk.",
                    sr="Voorbeeld: content van jouw merk op Instagram, TikTok, YouTube, LinkedIn, je blog in Google en Facebook.",
                    links=[("instagram","Instagram"),("tiktok","TikTok"),("youtube","YouTube"),("wordpress","WordPress")],
                    kaarten=[("instagram","Instagram","Reels","social"),("tiktok","TikTok","","social"),("youtube","YouTube","","social"),
                             ("linkedin","LinkedIn","","social"),("google","Google","Blog","snippet"),("facebook","Facebook","","social")]),
    "ai": dict(pill="Wat AI voor je doet", t1="Jouw marketing", t2="sneller met AI", vraag="Schrijf een eerste versie van...",
               lead="De student zet AI-tools in waar ze je team echt tijd besparen, en een mens controleert de output.",
               sr="Voorbeeld: AI-assistenten als ChatGPT, Claude, Gemini, Perplexity en Copilot ingezet voor jouw marketing, en jouw bedrijf genoemd in Google AI-antwoorden.",
               links=[("openai","ChatGPT"),("claude","Claude"),("googlegemini","Gemini"),("perplexity","Perplexity")],
               kaarten=[("openai","ChatGPT","","chat"),("claude","Claude","","chat"),("googlegemini","Gemini","","chat"),
                        ("perplexity","Perplexity","","chat"),("microsoft","Copilot","","chat"),("google","Google","AI-overzicht","chat")]),
    "claude": dict(pill="Wat Claude voor je doet", t1="Claude", t2="aan het werk voor jou", vraag="Vat deze klantvragen samen...",
                   lead="De student richt Claude in voor jouw team: vaste instructies, jouw kennis en duidelijke controle.",
                   sr="Voorbeeld: Claude ingezet voor content, samenvattingen, klantvragen en analyses.",
                   links=[("claude","Claude")],
                   kaarten=[("claude","Claude","Content","chat"),("claude","Claude","Samenvatting","chat"),("claude","Claude","Klantvragen","chat"),
                            ("claude","Claude","Analyse","chat"),("claude","Claude","Briefing","chat"),("google","Google","Zoeken","serp")]),
    "tiktok": dict(pill="Voorbeeld van het resultaat", t1="Jouw merk", t2="op TikTok", vraag="nieuwe collectie",
                   lead="Video's die passen bij het platform, in een vast ritme. De student maakt en post, de senior bewaakt je merk.",
                   sr="Voorbeeld: video's van jouw merk op TikTok, hergebruikt op Instagram Reels en YouTube Shorts.",
                   links=[("tiktok","TikTok"),("instagram","Reels"),("youtube","Shorts")],
                   kaarten=[("tiktok","TikTok","Voor jou","social"),("tiktok","TikTok","Volgend","social"),("instagram","Instagram","Reels","social"),
                            ("tiktok","TikTok","Zoeken","social"),("youtube","YouTube","Shorts","social"),("tiktok","TikTok","Advertentie","social")]),
    "instagram": dict(pill="Voorbeeld van het resultaat", t1="Jouw merk", t2="op Instagram", vraag="nieuwe collectie",
                      lead="Een feed die klopt, stories en reels in een vast ritme. De student maakt en plant, de senior bewaakt je merk.",
                      sr="Voorbeeld: posts, stories, reels en advertenties van jouw merk op Instagram en Facebook.",
                      links=[("instagram","Instagram"),("facebook","Facebook"),("meta","Meta")],
                      kaarten=[("instagram","Instagram","Feed","social"),("instagram","Instagram","Reels","social"),("instagram","Instagram","Stories","social"),
                               ("facebook","Facebook","","social"),("instagram","Instagram","Gesponsord","social"),("instagram","Instagram","Verkennen","social")]),
    "linkedin": dict(pill="Voorbeeld van het resultaat", t1="Jouw bedrijf", t2="zichtbaar op LinkedIn", vraag="onze aanpak",
                     lead="Posts die gelezen worden door de mensen die bij je kopen. De student schrijft en plant, de senior bewaakt je toon.",
                     sr="Voorbeeld: posts en advertenties van jouw bedrijf op LinkedIn en je bedrijf in Google.",
                     links=[("linkedin","LinkedIn")],
                     kaarten=[("linkedin","LinkedIn","Bedrijfspagina","social"),("linkedin","LinkedIn","Profiel","social"),("linkedin","LinkedIn","Gesponsord","social"),
                              ("linkedin","LinkedIn","Artikel","social"),("linkedin","LinkedIn","Nieuwsbrief","social"),("google","Google","Zoeken","serp")]),
}

PLAT = {
    "seo": [("google","Google","Zoeken, Maps en Search Console"),("microsoft","Bing","Bing Webmaster Tools"),("openai","ChatGPT","Vindbaar in AI-antwoorden"),("perplexity","Perplexity","Genoemd als bron"),("wordpress","WordPress","On-page SEO en content")],
    "ads": [("googleads","Google Ads","Zoeken, Display en Performance Max"),("google","Google Merchant Center","Shopping en productfeed"),("microsoft","Microsoft Ads","Bing en partners"),("youtube","YouTube","Videoadvertenties"),("meta","Meta","Facebook- en Instagram-ads")],
    "social": [("instagram","Instagram","Feed, stories en reels"),("facebook","Facebook","Pagina en groepen"),("linkedin","LinkedIn","Zakelijke content"),("tiktok","TikTok","Korte video"),("youtube","YouTube","Video en Shorts"),("meta","Meta Business Suite","Plannen en ads")],
    "ai": [("openai","ChatGPT","Tekst en analyse"),("claude","Claude","Content en processen"),("googlegemini","Gemini","Google Workspace"),("perplexity","Perplexity","Onderzoek met bronnen"),("microsoft","Copilot","Microsoft 365")],
    "content": [("instagram","Instagram","Reels en posts"),("tiktok","TikTok","Korte video"),("youtube","YouTube","Video en Shorts"),("linkedin","LinkedIn","Zakelijke content"),("wordpress","WordPress","Blogs en pagina's")],
    "wordpress": [("wordpress","WordPress","Pagina's en onderhoud"),("woo","WooCommerce","Webshop"),("google","Google Search Console","Vindbaarheid")],
    "instagram": [("instagram","Instagram","Feed, stories en reels"),("facebook","Facebook","Gekoppelde pagina"),("meta","Meta Business Suite","Plannen en ads")],
    "shopify": [("shopify","Shopify","Webshop en apps"),("google","Google Merchant Center","Shopping"),("meta","Meta","Catalogus en ads")],
}
