# Opbouw per dienstpagina, naar het model van social media uitbesteden:
# verhaal met animaties, wat zit er in een maand (of wat krijg je opgeleverd), en zo start je.
# Een rij is dict(t=kop, x=tekst, b=[3 punten], v=(soort, instellingen)); dict(reels=True, ...) toont de videoring.
# Cijfers in dashboards zijn voorbeelden en staan in de animatie gemarkeerd als "Voorbeeld".

STANDAARD_START = lambda derde, vierde: [
    ("Kennismaking", "We bespreken je doelen, je doelgroep en wat er nu al staat."),
    ("Toegang regelen", "Je geeft de student toegang via een eigen gebruiker of beheerdersrol. Je deelt geen wachtwoorden."),
    derde, vierde]

MAAND = "Wat zit er in *een maand?*"
OPLEVERING = "Wat krijg je *opgeleverd?*"

REELS_ROW = dict(reels=True, t="Content die *opvalt*",
                 x="Reels, carrousels en foto's in jouw huisstijl. De student bedenkt, filmt en monteert. Jij keurt alles goed voordat het online gaat. Tik op het luidsprekertje voor geluid.")

SOCIAL_DASH = dict(title="Social rapportage", sub="September · alle kanalen",
                   kpis=[("Bereik", "48.2", 1, "K", "48,2K", "+18%"), ("Interacties", "3140", 0, "", "3.140", "+24%"),
                         ("Linkklikken", "862", 0, "", "862", "+11%"), ("Nieuwe volgers", "214", 0, "", "214", "+9%")],
                   chart="Bereik per dag", bars_label="Interacties per kanaal",
                   bars=[("instagram", "Instagram", 46), ("linkedin", "LinkedIn", 28), ("facebook", "Facebook", 16), ("tiktok", "TikTok", 10)])

STORY = {
"social-media-uitbesteden": dict(
    intro="Van idee tot rapport: de student maakt je content, plant alles in, zet advertenties op en laat zien wat het oplevert. Een senior bewaakt je merk.",
    rows=[REELS_ROW,
          dict(t="Een contentkalender die *vol blijft*", x="Elke maand een planning met onderwerpen per kanaal. Je ziet vooraf wat er wanneer online gaat, en de student plant alles in.",
               b=["Planning per week en per kanaal", "Posts vooraf ter goedkeuring", "Ingepland via Meta Business Suite"], v=("calendar", {})),
          dict(t="Reacties en berichten *beantwoord*", x="Een post is pas af als je reageert. De student beantwoordt reacties en berichten in jouw toon. Vragen die bij jou horen, zoals een klacht of een offerteaanvraag, stuurt de student door.",
               b=["Reacties en DM's in jouw toon", "Vaste antwoorden op veelgestelde vragen", "Lastige vragen gaan naar jou"], v=("inbox", {})),
          dict(t="Social ads die de juiste mensen *bereiken*", x="Optioneel: met een klein budget je beste posts laten zien aan precies je doelgroep. De student zet campagnes op in Meta en LinkedIn, test varianten en stuurt bij.",
               b=["Doelgroep op regio, interesse en functie", "Varianten testen, de beste opschalen", "Werkt in je eigen advertentieaccount"], v=("adpost", {})),
          dict(t="Rapportage die je *snapt*", x="Elke maand een overzicht van bereik, interacties en klikken, met wat we volgende maand anders doen. Geen dik rapport, wel duidelijke keuzes.",
               b=["Cijfers per kanaal en per post", "Wat werkte en wat niet", "Plan voor de volgende maand"], v=("dashboard", SOCIAL_DASH))],
    month_t=MAAND, month_x="Je koopt geen losse posts, maar een vast ritme. Hoeveel posts en video's precies, hangt af van je uren en kanalen. Dat staat per maand in je offerte.",
    month=[("calendar", "Contentplan", "Onderwerpen en planning voor de maand, vooraf door jou goedgekeurd."),
           ("camera", "Posts, reels en stories", "Gemaakt en ingepland volgens de planning. Het aantal staat in je offerte."),
           ("users", "Community beheer", "Reacties en berichten beantwoord in jouw toon."),
           ("bar-chart", "Rapport en evaluatie", "Wat het opleverde, en wat we volgende maand anders doen.")],
    cta_t="Benieuwd wat er in jouw maand *past?*", cta_x="Vertel welke kanalen je hebt en wat je wilt bereiken. Je krijgt een voorstel met uren, content per maand en de student die het oppakt.",
    start_t="Zo start je *met social media*",
    start=[("Kennismaking", "We bespreken je doelen, je doelgroep en op welke kanalen je klanten zitten."),
           ("Toegang regelen", "Je geeft de student een beheerdersrol via Meta Business Suite en LinkedIn. Je deelt geen wachtwoorden."),
           ("Tone of voice vastleggen", "Je huisstijl en toon, met voorbeelden, zodat elke post klinkt als jij."),
           ("Eerste contentplan", "Jij keurt het plan goed, daarna maakt de student de content en gaat alles live.")]),

"seo-specialist-inhuren": dict(
    intro="Van zoekwoord tot rapport: de student zoekt uit waar je klanten op zoeken, maakt je site technisch gezond en schrijft content die gevonden wordt. Een senior SEO-specialist bewaakt de aanpak.",
    rows=[dict(t="Bovenaan waar je klanten *zoeken*", x="Het begint met zoekwoordonderzoek: welke zoekopdrachten leveren klanten op, en welke pagina hoort daarbij. Daarna werkt de student stap voor stap aan betere posities.",
               b=["Zoekwoorden met echte zoekvraag", "Eén pagina per onderwerp", "Titels en descriptions die klikken opleveren"], v=("serp", dict(query="installateur amersfoort"))),
          dict(t="Een website die technisch *klopt*", x="Google moet je site snel kunnen lezen. De student loopt de techniek na en lost op wat vindbaarheid tegenhoudt.",
               b=["Indexering en sitemap in orde", "Snelheid en mobiel gebruik", "Doorverwijzingen en kapotte links"],
               v=("checklist", dict(title="Technische SEO-check", items=["Pagina's geïndexeerd", "Sitemap ingediend", "Geen kapotte links", "Snel op mobiel", "Titels uniek", "Structured data", "Veilige verbinding (https)", "Doorverwijzingen kloppen"]))),
          dict(t="Content die *rankt*", x="Nieuwe pagina's en blogs rond de vragen van je klanten. De student plant de onderwerpen en schrijft ze, jij keurt goed.",
               b=["Contentplan op basis van zoekvraag", "Teksten in jouw toon", "Interne links naar je belangrijkste pagina's"],
               v=("calendar", dict(month="Oktober", status="blogs gepland", posts=[(0, "i:file", "Gids"), (2, "i:file", "Blog"), (4, "i:search", "FAQ"), (7, "i:file", "Blog"), (9, "i:layers", "Pagina"), (11, "i:file", "Blog")]))),
          dict(t="Rapportage die je *snapt*", x="Elke maand zie je wat er veranderde in posities, klikken en aanvragen, en wat de student volgende maand oppakt.",
               b=["Cijfers uit Search Console", "Welke pagina's stegen of daalden", "Plan voor de volgende maand"],
               v=("dashboard", dict(title="SEO-rapportage", sub="September · Google Search Console",
                                    kpis=[("Klikken", "1840", 0, "", "1.840", "+22%"), ("Vertoningen", "46.5", 1, "K", "46,5K", "+31%"),
                                          ("Gem. positie", "8.4", 1, "", "8,4", "+2,1"), ("CTR", "4.0", 1, "%", "4,0%", "+0,6")],
                                    chart="Klikken per dag", bars_label="Klikken per paginasoort",
                                    bars=[("i:layers", "Dienstpagina's", 52), ("i:file", "Blogs", 27), ("i:building", "Homepage", 15), ("i:map-pin", "Contact", 6)])))],
    month_t=MAAND, month_x="SEO is geen eenmalige klus maar een vast ritme. Wat er precies in een maand past, hangt af van je uren en staat in je offerte.",
    month=[("search", "Zoekwoorden en plan", "Welke onderwerpen en pagina's deze maand aan de beurt zijn."),
           ("zap", "Technische verbeteringen", "Wat vindbaarheid tegenhoudt, wordt opgelost."),
           ("file", "Content en optimalisatie", "Nieuwe teksten en bestaande pagina's beter gemaakt."),
           ("bar-chart", "Rapport en evaluatie", "Posities, klikken en het plan voor volgende maand.")],
    cta_t="Benieuwd wat SEO voor jou *oplevert?*", cta_x="Vertel om welke website het gaat en waar je gevonden wilt worden. Je krijgt een voorstel met uren, aanpak en de student die het oppakt.",
    start_t="Zo start je *met SEO*",
    start=STANDAARD_START(("Nulmeting", "De student brengt posities, techniek en content in kaart. Zo weet je waar je staat."),
                          ("Plan en eerste verbeteringen", "Jij keurt de prioriteiten goed, daarna gaat de student aan de slag."))),

"google-ads-specialist-inhuren": dict(
    intro="Van zoekwoord tot aanvraag: de student zet je campagnes op, meet wat ze opleveren en stuurt elke week bij. Een senior SEA-specialist kijkt mee.",
    rows=[dict(t="Bovenaan met je *advertentie*", x="Je advertentie verschijnt precies als iemand zoekt naar wat jij aanbiedt. De student kiest de zoekwoorden en schrijft advertenties die klikken opleveren.",
               b=["Zoekwoorden met koopintentie", "Advertenties per dienst of product", "Uitsluiten wat geen klanten oplevert"], v=("serp", dict(query="cv-ketel vervangen", ad=True))),
          dict(t="Campagnes die *kloppen*", x="Een goede campagne begint bij de basis. De student zet de structuur en de metingen goed neer, zodat je precies ziet wat een klik oplevert.",
               b=["Heldere campagnestructuur", "Conversiemeting via Google Tag Manager", "Negatieve zoekwoorden bijgehouden"],
               v=("checklist", dict(title="Campagne-check", items=["Conversies meten", "Zoekwoorden per advertentiegroep", "Negatieve zoekwoorden", "Advertentie-extensies", "Landingspagina past bij advertentie", "Budget per campagne", "Locatie en planning", "Doelgroepen voor remarketing"]))),
          dict(t="Rapportage die je *snapt*", x="Elke maand zie je wat je campagnes opleverden en wat de student heeft aangepast. Zonder vakjargon.",
               b=["Klikken, conversies en kosten per conversie", "Welke zoekwoorden werken", "Plan voor de volgende maand"],
               v=("dashboard", dict(title="Google Ads-rapportage", sub="September · alle campagnes",
                                    kpis=[("Klikken", "2310", 0, "", "2.310", "+14%"), ("Conversies", "96", 0, "", "96", "+19%"),
                                          ("CTR", "6.2", 1, "%", "6,2%", "+0,8"), ("Vertoningen", "37.1", 1, "K", "37,1K", "+9%")],
                                    chart="Conversies per dag", bars_label="Conversies per campagne",
                                    bars=[("i:search", "Zoeken", 58), ("i:cart", "Shopping", 24), ("i:refresh", "Remarketing", 12), ("youtube", "YouTube", 6)])))],
    month_t=MAAND, month_x="Een campagne loopt nooit vanzelf. Elke maand houdt de student hem scherp. Hoeveel uur daarvoor nodig is, staat in je offerte.",
    month=[("target", "Campagnebeheer", "Biedingen, budget en zoekwoorden bijgestuurd."),
           ("pen", "Advertenties testen", "Nieuwe varianten, de beste blijven."),
           ("check-circle", "Meting controleren", "Conversies kloppen en worden goed geteld."),
           ("bar-chart", "Rapport en evaluatie", "Resultaten en het plan voor volgende maand.")],
    cta_t="Benieuwd wat Google Ads voor jou *oplevert?*", cta_x="Vertel wat je verkoopt en in welke regio. Je krijgt een voorstel met uren, aanpak en de student die het oppakt.",
    start_t="Zo start je *met Google Ads*",
    start=STANDAARD_START(("Meting inrichten", "Conversies meten via Google Tag Manager, zodat je weet wat een klik oplevert."),
                          ("Campagnes live", "Jij keurt zoekwoorden, teksten en budget goed, daarna gaan de campagnes live."))),

"ai-specialist-inhuren": dict(
    intro="Van idee tot werkende workflow: de student zoekt uit waar AI je tijd bespaart, bouwt het in en leert je team ermee werken. Met duidelijke afspraken over privacy.",
    rows=[dict(t="AI die je werk *overneemt*", x="Van eerste versies van teksten tot samenvattingen van klantvragen. De student zet de assistent zo op dat de uitkomst klopt met jouw toon en werkwijze.",
               b=["Prompts en instructies op maat", "Controle voordat iets de deur uitgaat", "Werkt met ChatGPT, Claude en Gemini"],
               v=("chat", dict(tool="openai", name="ChatGPT", prompt="Schrijf een eerste versie van onze nieuwsbrief over de nieuwe openingstijden.", answer=["Onderwerp: Vanaf maandag langer open", "Goed nieuws: vanaf maandag zijn we tot 20.00 uur open.", "Zo kun je ook na je werk nog langs."]))),
          dict(t="Workflows die *vanzelf* lopen", x="Terugkerend werk automatisch laten verlopen. De student koppelt je tools en AI aan elkaar, zodat stappen zonder handwerk doorlopen.",
               b=["Koppelingen met Zapier of Make", "Vaste stappen, vaste kwaliteit", "Jij houdt het laatste woord"],
               v=("flow", dict(title="Automatische workflow", nodes=[("mail", "Nieuwe aanvraag", "Via je website"), ("bot", "AI vat samen", "Belangrijkste punten"), ("check-circle", "Controle", "Door jou of je team"), ("share", "In je CRM", "Klaar voor opvolging")]))),
          dict(t="Veilig en *verantwoord*", x="AI werkt pas als je erop kunt vertrouwen. De student maakt afspraken over data, controle en gebruik, en legt ze vast voor je team.",
               b=["Afspraken over welke data wel en niet", "Zakelijke abonnementen waar nodig", "Uitleg en training voor je team"],
               v=("checklist", dict(title="AI-afspraken", items=["Welke data mag erin", "Zakelijk account ingesteld", "Controle door een mens", "Vaste prompts vastgelegd", "Team getraind", "Afspraken gedeeld"])))],
    month_t=MAAND, month_x="Je begint met de toepassing die de meeste tijd bespaart en bouwt van daaruit verder. Hoeveel uur dat vraagt, staat in je offerte.",
    month=[("search", "Kansen in kaart", "Waar AI deze maand de meeste tijd bespaart."),
           ("bot", "Bouwen en testen", "Assistenten en workflows die werken."),
           ("users", "Team meenemen", "Uitleg en korte trainingen."),
           ("shield", "Privacy en kwaliteit", "Afspraken en controles bijgehouden.")],
    cta_t="Benieuwd wat AI jou *bespaart?*", cta_x="Vertel welk werk veel tijd kost. Je krijgt een voorstel met de eerste toepassingen, uren en de student die het oppakt.",
    start_t="Zo start je *met AI*",
    start=STANDAARD_START(("Eerste toepassing kiezen", "De taak die het meeste oplevert, met afspraken over data en controle."),
                          ("Bouwen en uitleggen", "De student bouwt het, test het met jou en legt je team uit hoe het werkt."))),

"claude-specialist-inhuren": dict(
    intro="Van projecten tot vaste werkwijze: de student richt Claude in voor jouw bedrijf, zodat je team sneller schrijft, samenvat en analyseert.",
    rows=[dict(t="Claude aan het werk *voor jou*", x="De student richt projecten in met je eigen documenten en instructies. Zo krijg je antwoorden die kloppen met jouw bedrijf.",
               b=["Projecten met je eigen kennis", "Instructies in jouw toon", "Sterk in lange documenten en rapporten"],
               v=("chat", dict(tool="claude", name="Claude", prompt="Vat deze 40 klantvragen samen en zet de belangrijkste thema's op een rij.", answer=["De drie meest gestelde vragen:", "1. Levertijd van maatwerk", "2. Garantie en onderhoud", "3. Mogelijkheden voor een showroombezoek"]))),
          dict(t="Vaste werkwijzen die *tijd sparen*", x="Terugkerende taken krijgen een vaste aanpak in Claude. Je team hoeft niet elke keer opnieuw te beginnen.",
               b=["Vaste prompts per taak", "Koppelingen waar het kan", "Controle door een mens"],
               v=("flow", dict(title="Werkwijze in Claude", nodes=[("file", "Document uploaden", "Offerte, rapport of notulen"), ("bot", "Claude analyseert", "Met jouw instructies"), ("pen", "Eerste versie", "Samenvatting of tekst"), ("check-circle", "Jij controleert", "En past aan waar nodig")]))),
          dict(t="Veilig en *verantwoord*", x="De student maakt afspraken over welke informatie in Claude mag, en zet een zakelijk account op waar dat nodig is.",
               b=["Afspraken over data", "Zakelijk account waar nodig", "Uitleg voor je team"],
               v=("checklist", dict(title="Claude-afspraken", items=["Welke data mag erin", "Zakelijk account ingesteld", "Projecten per team", "Vaste instructies", "Controle door een mens", "Team getraind"])))],
    month_t=MAAND, month_x="Je begint met één of twee toepassingen en breidt uit wat werkt. Hoeveel uur dat vraagt, staat in je offerte.",
    month=[("search", "Toepassingen kiezen", "Welke taken deze maand aan de beurt zijn."),
           ("layers", "Projecten inrichten", "Met je eigen documenten en instructies."),
           ("users", "Team meenemen", "Uitleg en korte trainingen."),
           ("shield", "Privacy en kwaliteit", "Afspraken en controles bijgehouden.")],
    cta_t="Benieuwd wat Claude jou *bespaart?*", cta_x="Vertel welk werk veel tijd kost. Je krijgt een voorstel met toepassingen, uren en de student die het oppakt.",
    start_t="Zo start je *met Claude*",
    start=STANDAARD_START(("Eerste project inrichten", "Met je eigen documenten, instructies en afspraken over data."),
                          ("Uitleggen en uitbreiden", "Je team leert ermee werken, daarna volgen de volgende toepassingen."))),

"contentmarketing-uitbesteden": dict(
    intro="Van plan tot publicatie: de student bedenkt en maakt foto, video en tekst voor je kanalen, en haalt uit elke opname zoveel mogelijk. Een senior bewaakt je merk.",
    rows=[REELS_ROW,
          dict(t="Een contentplan dat *klopt*", x="Onderwerpen die passen bij je doelgroep, verdeeld over je kanalen. Je ziet vooraf wat er komt en keurt het goed.",
               b=["Onderwerpen per maand", "Mix van foto, video en tekst", "Afgestemd op je doelen"],
               v=("calendar", dict(status="stukken content gepland", posts=[(0, "instagram", "Reel"), (1, "i:file", "Blog"), (3, "linkedin", "Case"), (4, "youtube", "Video"), (7, "i:mail", "Nieuwsbrief"), (8, "instagram", "Foto"), (10, "tiktok", "Video"), (11, "i:file", "Blog")]))),
          dict(t="Eén opname, *veel content*", x="Van één draaidag maakt de student reels, foto's, een blog en posts. Zo haal je meer uit elke opname.",
               b=["Montage voor elk formaat", "Ondertiteling en huisstijl", "Klaar voor elk kanaal"], v=("editor", {}))],
    month_t=MAAND, month_x="Een vast ritme van content werkt beter dan af en toe een piek. Hoeveel stukken per maand, staat in je offerte.",
    month=[("calendar", "Contentplan", "Onderwerpen en formats voor de maand."),
           ("camera", "Foto en video", "Opnames en montage."),
           ("pen", "Teksten", "Blogs, captions en webteksten."),
           ("bar-chart", "Evaluatie", "Wat werkte, en wat we volgende maand maken.")],
    cta_t="Benieuwd wat er in jouw maand *past?*", cta_x="Vertel voor welke kanalen je content nodig hebt. Je krijgt een voorstel met uren, content per maand en de student die het oppakt.",
    start_t="Zo start je *met contentmarketing*",
    start=STANDAARD_START(("Stijl vastleggen", "Je huisstijl, toon en voorbeelden die je mooi vindt."),
                          ("Eerste contentplan", "Jij keurt het plan goed, daarna gaat de student maken."))),

"foto-en-video-laten-maken": dict(
    intro="Van script tot montage: de student bedenkt, filmt en fotografeert, en levert alles op in de juiste formaten voor je kanalen.",
    rows=[REELS_ROW,
          dict(t="Van opname tot *montage*", x="De student monteert in Premiere Pro, After Effects of DaVinci Resolve. Met ondertiteling, muziek en jouw huisstijl.",
               b=["Montage en ondertiteling", "Motion graphics en animatie", "Kleurcorrectie"], v=("editor", {})),
          dict(t="Klaar als *advertentie*", x="Een goede video werkt ook als advertentie. De student levert versies op die je direct kunt inzetten op Meta, TikTok en YouTube.",
               b=["Verticaal, vierkant en liggend", "Korte en lange versie", "Klaar voor adverteren"], v=("adpost", dict(img="/assets/video/showroom-reel.webp", cta="Plan een proefrit", btn="Meer informatie")))],
    month_t=OPLEVERING, month_x="Of het nu om één bedrijfsvideo gaat of om een vaste reeks: vooraf spreek je af wat je krijgt.",
    month=[("pen", "Concept en script", "Wat we laten zien, en aan wie."),
           ("camera", "Opnames", "Op locatie of met je eigen materiaal."),
           ("layers", "Montage", "Met ondertiteling, muziek en huisstijl."),
           ("share", "Alle formaten", "Klaar voor elk kanaal en voor advertenties.")],
    cta_t="Benieuwd wat we voor jou *maken?*", cta_x="Vertel wat je in beeld wilt brengen. Je krijgt een voorstel met aanpak, planning en de student die het oppakt.",
    start_t="Zo start je *met foto en video*",
    start=[("Kennismaking", "Wat wil je laten zien, aan wie en op welk kanaal."),
           ("Concept en planning", "Script, shotlist en een datum voor de opnames."),
           ("Opnames", "Op locatie, of met materiaal dat je zelf aanlevert."),
           ("Montage en oplevering", "Je geeft feedback, daarna krijg je alle formaten.")]),

"premiere-pro-editor-inhuren": dict(
    intro="Montage in Adobe Premiere Pro: de student maakt van je ruwe opnames een video die klaar is voor je kanalen, met ondertiteling en jouw huisstijl.",
    rows=[REELS_ROW,
          dict(t="Montage die *loopt*", x="Ritme, muziek en ondertiteling maken het verschil. De student monteert je beelden tot een video die mensen uitkijken.",
               b=["Montage op ritme en muziek", "Ondertiteling in je huisstijl", "Intro en afsluiting met je logo"], v=("editor", {})),
          dict(t="Eén opname, *alle formaten*", x="Van één montage maakt de student versies voor Reels, TikTok, YouTube en je website.",
               b=["9:16, 1:1 en 16:9", "Korte en lange versie", "Klaar voor adverteren"], v=("adpost", dict(img="/assets/video/verhuis-commercial.webp", cta="Vraag een offerte aan", btn="Meer informatie")))],
    month_t=OPLEVERING, month_x="Per video of als vaste reeks per maand. Vooraf spreek je af wat je krijgt.",
    month=[("file", "Materiaal doornemen", "Je beelden, logo en huisstijl."),
           ("layers", "Montage", "Ritme, muziek en overgangen."),
           ("pen", "Ondertiteling", "In je huisstijl, goed leesbaar."),
           ("share", "Alle formaten", "Klaar voor elk kanaal.")],
    cta_t="Benieuwd wat we van je beelden *maken?*", cta_x="Vertel wat voor video je nodig hebt. Je krijgt een voorstel met aanpak, planning en de student die het oppakt.",
    start_t="Zo start je *met montage*",
    start=[("Kennismaking", "Wat voor video, voor welk kanaal en welke stijl."),
           ("Materiaal aanleveren", "Je deelt je opnames via een gedeelde map."),
           ("Eerste montage", "De student maakt een eerste versie."),
           ("Feedback en oplevering", "Je geeft feedback, daarna krijg je alle formaten.")]),

"after-effects-specialist-inhuren": dict(
    intro="Motion graphics en animatie in Adobe After Effects: de student laat je logo, cijfers en boodschap bewegen, in jouw huisstijl.",
    rows=[REELS_ROW,
          dict(t="Beweging die je merk *versterkt*", x="Een bewegend logo, geanimeerde tekst of een uitlegvideo. De student maakt het in After Effects, passend bij je huisstijl.",
               b=["Logo-animaties en intro's", "Geanimeerde teksten en ondertitels", "Uitlegvideo's met iconen"], v=("brand", {})),
          dict(t="Animatie in je *video's*", x="Motion graphics maken een video duidelijker. De student voegt titels, pijlen en cijfers toe aan je montage.",
               b=["Titels en lower thirds", "Geanimeerde cijfers en grafieken", "Overgangen in je huisstijl"], v=("editor", {}))],
    month_t=OPLEVERING, month_x="Per animatie of als vaste reeks per maand. Vooraf spreek je af wat je krijgt.",
    month=[("pen", "Concept en storyboard", "Wat er beweegt, en waarom."),
           ("layers", "Animatie", "In After Effects, in je huisstijl."),
           ("zap", "Feedbackronde", "Je ziet een versie en geeft feedback."),
           ("share", "Alle formaten", "Klaar voor video, social en je website.")],
    cta_t="Benieuwd wat we kunnen *animeren?*", cta_x="Vertel wat je wilt laten bewegen. Je krijgt een voorstel met aanpak, planning en de student die het oppakt.",
    start_t="Zo start je *met animatie*",
    start=[("Kennismaking", "Wat moet er bewegen, waar komt het te staan."),
           ("Storyboard", "Een schets van de animatie, ter goedkeuring."),
           ("Animatie maken", "De student animeert in After Effects."),
           ("Feedback en oplevering", "Je geeft feedback, daarna krijg je alle bestanden.")]),

"davinci-resolve-editor-inhuren": dict(
    intro="Montage en kleurcorrectie in DaVinci Resolve: de student geeft je beelden een professionele, consistente look.",
    rows=[REELS_ROW,
          dict(t="Kleur die *klopt*", x="Kleurcorrectie maakt beelden rustig en herkenbaar. De student zorgt dat al je video's dezelfde look hebben, passend bij je merk.",
               b=["Kleurcorrectie en color grading", "Eén look voor al je video's", "Huidtinten en licht natuurlijk"], v=("editor", {})),
          dict(t="Eén opname, *alle formaten*", x="Na de montage levert de student versies op voor Reels, TikTok, YouTube en je website.",
               b=["9:16, 1:1 en 16:9", "Korte en lange versie", "Klaar voor adverteren"], v=("adpost", dict(img="/assets/video/speedboot-reel.webp", cta="Boek je vaartocht", btn="Meer informatie")))],
    month_t=OPLEVERING, month_x="Per video of als vaste reeks per maand. Vooraf spreek je af wat je krijgt.",
    month=[("file", "Materiaal doornemen", "Je beelden en gewenste look."),
           ("layers", "Montage", "Ritme, muziek en overgangen."),
           ("zap", "Kleurcorrectie", "Een consistente look in DaVinci Resolve."),
           ("share", "Alle formaten", "Klaar voor elk kanaal.")],
    cta_t="Benieuwd wat we van je beelden *maken?*", cta_x="Vertel wat voor video je nodig hebt. Je krijgt een voorstel met aanpak, planning en de student die het oppakt.",
    start_t="Zo start je *met DaVinci Resolve*",
    start=[("Kennismaking", "Wat voor video en welke look past bij je merk."),
           ("Materiaal aanleveren", "Je deelt je opnames via een gedeelde map."),
           ("Montage en kleur", "De student monteert en corrigeert de kleur."),
           ("Feedback en oplevering", "Je geeft feedback, daarna krijg je alle formaten.")]),

"recruitment-marketing-uitbesteden": dict(
    intro="Van vacaturetekst tot sollicitatie: de student maakt je vacatures zichtbaar bij de juiste kandidaten en laat zien wat het oplevert.",
    rows=[dict(t="Vacatures die *opvallen*", x="Een vacature is ook een advertentie. De student schrijft wervende teksten en zet ze als campagne in op de kanalen waar je kandidaten zitten.",
               b=["Wervende vacatureteksten", "Campagnes op LinkedIn en Meta", "Gericht op functie en regio"],
               v=("adpost", dict(img="/assets/img/foto/team-overleg-800.webp", cta="Wij zoeken een collega", btn="Solliciteer", counter="reacties op je vacature"))),
          dict(t="Laten zien hoe het is om *bij jou te werken*", x="Kandidaten willen weten wie je bent. De student maakt content over je team en werkplek en plant die in.",
               b=["Verhalen van je medewerkers", "Posts rond je vacatures", "Een werkenbij-pagina die overtuigt"],
               v=("calendar", dict(status="posts gepland", posts=[(0, "linkedin", "Vacature"), (2, "instagram", "Team"), (4, "linkedin", "Verhaal"), (7, "facebook", "Vacature"), (9, "instagram", "Werkplek"), (11, "linkedin", "Vacature")]))),
          dict(t="Rapportage die je *snapt*", x="Je ziet welke kanalen sollicitaties opleveren en waar je beter mee stopt.",
               b=["Sollicitaties per kanaal", "Kosten per sollicitatie", "Plan voor de volgende maand"],
               v=("dashboard", dict(title="Recruitment-rapportage", sub="September · alle vacatures",
                                    kpis=[("Bereik", "21.4", 1, "K", "21,4K", "+26%"), ("Klikken", "940", 0, "", "940", "+17%"),
                                          ("Sollicitaties", "38", 0, "", "38", "+12"), ("Gesprekken", "11", 0, "", "11", "+4")],
                                    chart="Klikken op vacatures per dag", bars_label="Sollicitaties per kanaal",
                                    bars=[("linkedin", "LinkedIn", 45), ("meta", "Meta", 30), ("google", "Google", 17), ("i:building", "Werkenbij", 8)])))],
    month_t=MAAND, month_x="Zolang je vacatures open staan, houdt de student ze zichtbaar. Hoeveel uur dat vraagt, staat in je offerte.",
    month=[("pen", "Vacatureteksten", "Nieuwe en bijgewerkte vacatures."),
           ("target", "Campagnes", "Ingezet en bijgestuurd per kanaal."),
           ("camera", "Employer branding", "Content over je team en werkplek."),
           ("bar-chart", "Rapport en evaluatie", "Sollicitaties per kanaal en het plan.")],
    cta_t="Benieuwd hoe je *kandidaten bereikt?*", cta_x="Vertel welke vacatures open staan. Je krijgt een voorstel met aanpak, uren en de student die het oppakt.",
    start_t="Zo start je *met recruitment marketing*",
    start=STANDAARD_START(("Werkgeversverhaal vastleggen", "Wat maakt jou een goede werkgever, en voor wie."),
                          ("Eerste campagne", "Jij keurt teksten en doelgroep goed, daarna gaat de vacature live."))),

"huisstijl-laten-maken": dict(
    intro="Van merkonderzoek tot merkhandboek: de student ontwerpt je logo, kleuren en toon, en legt alles vast zodat iedereen er consequent mee werkt.",
    rows=[dict(t="Een merk dat je *herkent*", x="Logo, kleuren en lettertypen die bij je passen. De student ontwerpt in rondes, tot het klopt.",
               b=["Logo en beeldmerk", "Kleurenpalet en typografie", "Ontwerprondes tot het klopt"], v=("brand", {})),
          dict(t="Alles vastgelegd in *één handboek*", x="Een huisstijl werkt pas als iedereen hem goed gebruikt. De student legt alle afspraken vast in een merkhandboek.",
               b=["Regels voor logo en kleur", "Tone of voice met voorbeelden", "Templates voor social en presentaties"],
               v=("checklist", dict(title="Merkhandboek", items=["Logo en varianten", "Kleurenpalet", "Lettertypen", "Beeldstijl", "Tone of voice", "Social media-templates", "Presentatiesjabloon", "Visitekaartje"])))],
    month_t=OPLEVERING, month_x="Een huisstijl is een project met een duidelijk einde. Vooraf spreek je af wat je krijgt.",
    month=[("search", "Merkonderzoek", "Wie je bent, voor wie, en wat je anders maakt."),
           ("pen", "Logo en beeldmerk", "Ontworpen in rondes."),
           ("layers", "Kleur en typografie", "Een palet dat overal werkt."),
           ("file", "Merkhandboek", "Alle bestanden en afspraken op één plek.")],
    cta_t="Benieuwd hoe jouw merk *eruit kan zien?*", cta_x="Vertel over je bedrijf en wat je nodig hebt. Je krijgt een voorstel met aanpak, planning en de student die het oppakt.",
    start_t="Zo start je *met je huisstijl*",
    start=[("Kennismaking", "Over je bedrijf, je klanten en wat je mooi vindt."),
           ("Merkonderzoek", "De student zet je merk en je doelgroep op papier."),
           ("Ontwerprondes", "Eerste ontwerpen, jouw feedback, en verfijnen."),
           ("Oplevering", "Alle bestanden en het merkhandboek.")]),

"email-marketing-uitbesteden": dict(
    intro="Van nieuwsbrief tot automatische flow: de student schrijft en verstuurt je mails, en zet flows op die vanzelf lopen.",
    rows=[dict(t="Nieuwsbrieven die *geopend* worden", x="Een goede onderwerpregel, een duidelijke boodschap en een knop die opvalt. De student schrijft en ontwerpt je nieuwsbrief in je huisstijl.",
               b=["Tekst en ontwerp in je huisstijl", "Onderwerpregels getest", "Pas verstuurd na jouw akkoord"],
               v=("inbox", dict(title="Inbox van je klant", channels=["i:mail"], msgs=[("in", "JB", "Nieuw: onze herfstcollectie is binnen"), ("in", "JB", "Laatste kans: 3 tips voor je tuin"), ("in", "JB", "Welkom! Dit kun je van ons verwachten")]))),
          dict(t="Flows die *vanzelf lopen*", x="Een welkomstreeks, een herinnering bij een verlaten winkelwagen of een mail na aankoop. Eén keer goed opgezet, daarna loopt het vanzelf.",
               b=["Welkom en onboarding", "Verlaten winkelwagen", "Heractivatie van oude klanten"],
               v=("flow", dict(title="Welkomstflow", nodes=[("users", "Nieuwe inschrijving", "Via je website"), ("mail", "Welkomstmail", "Direct"), ("clock", "Na 3 dagen", "Tips en inspiratie"), ("cart", "Na 7 dagen", "Een aanbod op maat")]))),
          dict(t="Rapportage die je *snapt*", x="Je ziet wie opent, klikt en koopt, en wat de student de volgende keer beter doet.",
               b=["Opens en kliks per mail", "Wat een flow oplevert", "Plan voor de volgende maand"],
               v=("dashboard", dict(title="E-mailrapportage", sub="September · nieuwsbrieven en flows",
                                    kpis=[("Verzonden", "12.8", 1, "K", "12,8K", "+8%"), ("Opens", "42", 0, "%", "42%", "+5"),
                                          ("Kliks", "6.1", 1, "%", "6,1%", "+1,2"), ("Afmeldingen", "0.3", 1, "%", "0,3%", "-0,1")],
                                    chart="Kliks per dag", bars_label="Kliks per soort mail",
                                    bars=[("i:mail", "Nieuwsbrief", 48), ("i:users", "Welkom", 27), ("i:cart", "Winkelwagen", 18), ("i:refresh", "Heractivatie", 7)])))],
    month_t=MAAND, month_x="Een vast ritme in de mailbox van je klanten. Hoeveel mails en flows per maand, staat in je offerte.",
    month=[("mail", "Nieuwsbrieven", "Geschreven, ontworpen en verstuurd."),
           ("refresh", "Flows", "Opgezet en verbeterd."),
           ("users", "Segmentatie", "De juiste mail naar de juiste groep."),
           ("bar-chart", "Rapport en evaluatie", "Wat het opleverde, en het plan.")],
    cta_t="Benieuwd wat e-mail jou *oplevert?*", cta_x="Vertel welke mailtool je gebruikt en wat je wilt bereiken. Je krijgt een voorstel met uren en de student die het oppakt.",
    start_t="Zo start je *met e-mailmarketing*",
    start=STANDAARD_START(("Lijst en privacy nalopen", "Toestemming, afmelden en segmenten goed geregeld."),
                          ("Eerste mail of flow", "Jij keurt de eerste mail goed, daarna gaat hij de deur uit."))),

"wordpress-specialist-inhuren": dict(
    intro="Van nieuwe pagina tot onderhoud: de student bouwt en verbetert je WordPress-site, en houdt hem snel en veilig.",
    rows=[dict(t="Pagina's die *staan*", x="Nieuwe pagina's in je bestaande thema of pagebuilder, zodat alles herkenbaar blijft.",
               b=["Werkt in je eigen thema", "Landingspagina's en dienstpagina's", "Mobiel netjes"], v=("builder", {})),
          dict(t="Snel op *elk scherm*", x="Een trage site kost bezoekers en posities in Google. De student maakt je site sneller.",
               b=["Afbeeldingen geoptimaliseerd", "Caching ingesteld", "Overbodige plugins weg"], v=("gauge", {})),
          dict(t="Veilig en *bijgewerkt*", x="Updates, back-ups en beveiliging, elke maand. Zo voorkom je problemen in plaats van ze op te lossen.",
               b=["WordPress en plugins bijgewerkt", "Back-ups gecontroleerd", "Beveiliging nagelopen"],
               v=("checklist", dict(title="Maandelijks onderhoud", items=["WordPress bijgewerkt", "Plugins bijgewerkt", "Thema bijgewerkt", "Back-up gecontroleerd", "Formulieren getest", "Kapotte links opgelost", "Beveiliging nagelopen", "Snelheid gemeten"])))],
    month_t=MAAND, month_x="Onderhoud en verbeteringen in een vast ritme. Hoeveel uur dat vraagt, staat in je offerte.",
    month=[("refresh", "Updates", "WordPress, plugins en thema."),
           ("shield", "Back-ups en beveiliging", "Gecontroleerd en in orde."),
           ("zap", "Snelheid", "Gemeten en verbeterd."),
           ("layers", "Nieuwe pagina's", "Gebouwd en aangepast waar nodig.")],
    cta_t="Benieuwd wat er aan je site *beter kan?*", cta_x="Stuur je websiteadres mee. Je krijgt een voorstel met aanpak, uren en de student die het oppakt.",
    start_t="Zo start je *met je WordPress-site*",
    start=STANDAARD_START(("Site doorlichten", "Snelheid, updates, beveiliging en SEO-basis in kaart."),
                          ("Plan en eerste verbeteringen", "Jij keurt de prioriteiten goed, daarna gaat de student aan de slag."))),

"shopify-specialist-inhuren": dict(
    intro="Van productpagina tot rapport: de student houdt je webshop bij, verbetert productpagina's en koppelt de apps die je nodig hebt.",
    rows=[dict(t="Productpagina's die *verkopen*", x="Goede foto's, duidelijke teksten en een knop die opvalt. De student zet je producten er netjes en vindbaar in.",
               b=["Productteksten die overtuigen", "Foto's en varianten op orde", "Vindbaar in Google"], v=("product", {})),
          dict(t="Een webshop die *klopt*", x="Thema, apps en koppelingen die goed samenwerken. De student houdt het overzicht en lost op wat hapert.",
               b=["Thema en pagina's aangepast", "Apps en koppelingen", "Google Merchant Center voor Shopping"],
               v=("checklist", dict(title="Webshop-check", items=["Producten compleet", "Varianten en voorraad", "Afrekenen getest", "Verzendregels", "Google Shopping-feed", "Snelheid", "Juridische pagina's", "Mails na bestelling"]))),
          dict(t="Rapportage die je *snapt*", x="Je ziet wat er verkocht wordt, via welke kanalen, en wat de student volgende maand verbetert.",
               b=["Bezoekers en conversie", "Bestsellers en kanalen", "Plan voor de volgende maand"],
               v=("dashboard", dict(title="Webshop-rapportage", sub="September · alle kanalen",
                                    kpis=[("Bezoekers", "14.2", 1, "K", "14,2K", "+16%"), ("Bestellingen", "312", 0, "", "312", "+21%"),
                                          ("Conversie", "2.2", 1, "%", "2,2%", "+0,3"), ("Terugkerend", "34", 0, "%", "34%", "+4")],
                                    chart="Bestellingen per dag", bars_label="Bestellingen per kanaal",
                                    bars=[("google", "Google", 41), ("meta", "Meta", 26), ("i:mail", "E-mail", 21), ("i:link", "Direct", 12)])))],
    month_t=MAAND, month_x="Je webshop bijhouden en verbeteren in een vast ritme. Hoeveel uur dat vraagt, staat in je offerte.",
    month=[("bag", "Productbeheer", "Nieuwe producten en aanpassingen."),
           ("pen", "Productteksten", "Overtuigend en vindbaar."),
           ("layers", "Thema en apps", "Aangepast en gekoppeld."),
           ("bar-chart", "Rapport en evaluatie", "Verkoop per kanaal en het plan.")],
    cta_t="Benieuwd wat er aan je webshop *beter kan?*", cta_x="Stuur je webshopadres mee. Je krijgt een voorstel met aanpak, uren en de student die het oppakt.",
    start_t="Zo start je *met je Shopify-winkel*",
    start=STANDAARD_START(("Webshop doorlichten", "Producten, thema, apps en snelheid in kaart."),
                          ("Plan en eerste verbeteringen", "Jij keurt de prioriteiten goed, daarna gaat de student aan de slag."))),

"instagram-uitbesteden": dict(
    intro="Van feed tot DM: de student maakt en plant je posts, reels en stories, en reageert op je volgers. Een senior bewaakt je merk.",
    rows=[REELS_ROW,
          dict(t="Een feed die *vol blijft*", x="Elke maand een planning met posts, reels en stories. Je ziet vooraf wat er komt en keurt het goed.",
               b=["Mix van posts, reels en stories", "Captions en hashtags", "Ingepland via Meta Business Suite"],
               v=("calendar", dict(posts=[(0, "instagram", "Reel"), (1, "instagram", "Story"), (3, "instagram", "Post"), (4, "instagram", "Reel"), (7, "instagram", "Carrousel"), (8, "instagram", "Story"), (10, "instagram", "Reel"), (12, "instagram", "Post")]))),
          dict(t="Reacties en DM's *beantwoord*", x="De student reageert op je volgers in jouw toon. Vragen die bij jou horen, stuurt de student door.",
               b=["Reacties en DM's in jouw toon", "Vaste antwoorden op veelgestelde vragen", "Lastige vragen gaan naar jou"],
               v=("inbox", dict(title="Instagram-berichten", channels=["instagram"]))),
          dict(t="Instagram-advertenties die *bereiken*", x="Optioneel: je beste posts laten zien aan precies je doelgroep, met een klein budget.",
               b=["Doelgroep op regio en interesse", "Varianten testen", "Werkt in je eigen advertentieaccount"], v=("adpost", {}))],
    month_t=MAAND, month_x="Je koopt geen losse posts, maar een vast ritme. Hoeveel posts en reels precies, staat in je offerte.",
    month=[("calendar", "Contentplan", "Posts, reels en stories voor de maand."),
           ("camera", "Maken en plannen", "Foto's, reels en captions."),
           ("users", "Community beheer", "Reacties en DM's beantwoord."),
           ("bar-chart", "Rapport en evaluatie", "Wat werkte, en het plan.")],
    cta_t="Benieuwd wat er in jouw maand *past?*", cta_x="Vertel wat je met Instagram wilt bereiken. Je krijgt een voorstel met uren, content per maand en de student die het oppakt.",
    start_t="Zo start je *met Instagram*",
    start=[("Kennismaking", "Je doelen, je doelgroep en je huidige account."),
           ("Toegang regelen", "Via Meta Business Suite. Je deelt geen wachtwoorden."),
           ("Stijl vastleggen", "Je huisstijl, toon en voorbeelden die je mooi vindt."),
           ("Eerste contentplan", "Jij keurt het plan goed, daarna gaat alles live.")]),

"tiktok-uitbesteden": dict(
    intro="Van trend tot video: de student bedenkt, filmt en monteert TikToks die passen bij je merk, en plant ze in.",
    rows=[REELS_ROW,
          dict(t="Een vast *ritme*", x="Op TikTok telt regelmaat. De student plant je video's in, afgestemd op trends en je doelgroep.",
               b=["Trends vertaald naar jouw merk", "Vaste dagen en tijden", "Posts vooraf ter goedkeuring"],
               v=("calendar", dict(status="video's gepland", posts=[(0, "tiktok", "Trend"), (2, "tiktok", "Tips"), (4, "tiktok", "Team"), (7, "tiktok", "Trend"), (9, "tiktok", "Uitleg"), (11, "tiktok", "Trend")]))),
          dict(t="Van opname tot *montage*", x="Snel, met ondertiteling en muziek die past. De student monteert in het tempo van TikTok.",
               b=["Montage in TikTok-tempo", "Ondertiteling en tekst in beeld", "Muziek en geluid"], v=("editor", {})),
          dict(t="Rapportage die je *snapt*", x="Je ziet welke video's werken en wat de student volgende maand maakt.",
               b=["Weergaven en kijkduur", "Beste video's van de maand", "Plan voor de volgende maand"],
               v=("dashboard", dict(title="TikTok-rapportage", sub="September · alle video's",
                                    kpis=[("Weergaven", "86.4", 1, "K", "86,4K", "+34%"), ("Likes", "5210", 0, "", "5.210", "+27%"),
                                          ("Shares", "412", 0, "", "412", "+19%"), ("Nieuwe volgers", "638", 0, "", "638", "+22%")],
                                    chart="Weergaven per dag", bars_label="Weergaven per soort video",
                                    bars=[("i:trending", "Trends", 44), ("i:zap", "Tips", 29), ("i:users", "Team", 17), ("i:play", "Uitleg", 10)])))],
    month_t=MAAND, month_x="Een vast ritme van video's. Hoeveel per maand, staat in je offerte.",
    month=[("trending", "Trends en ideeën", "Vertaald naar jouw merk."),
           ("camera", "Filmen", "Op locatie of met je eigen materiaal."),
           ("layers", "Monteren en plannen", "Met ondertiteling en muziek."),
           ("bar-chart", "Rapport en evaluatie", "Wat werkte, en het plan.")],
    cta_t="Benieuwd wat TikTok jou *oplevert?*", cta_x="Vertel wat je met TikTok wilt bereiken. Je krijgt een voorstel met uren, video's per maand en de student die het oppakt.",
    start_t="Zo start je *met TikTok*",
    start=[("Kennismaking", "Past TikTok bij je doelgroep, en wat wil je laten zien."),
           ("Account en toegang", "Een zakelijk account en toegang zonder wachtwoorden te delen."),
           ("Stijl en formats", "De soort video's die bij je passen."),
           ("Eerste video's", "Jij keurt goed, daarna gaat alles live.")]),

"linkedin-marketing-uitbesteden": dict(
    intro="Van bedrijfspagina tot persoonlijk profiel: de student schrijft en plant je posts, reageert op je netwerk en zet advertenties in waar dat helpt.",
    rows=[dict(t="Posts die *gelezen* worden", x="Kennis, klantverhalen en nieuws uit je bedrijf, in jouw toon. De student schrijft en plant, jij keurt goed.",
               b=["Bedrijfspagina en persoonlijk profiel", "Klantverhalen en kennis", "Posts vooraf ter goedkeuring"],
               v=("calendar", dict(posts=[(0, "linkedin", "Kennis"), (2, "linkedin", "Case"), (4, "linkedin", "Nieuws"), (7, "linkedin", "Vacature"), (9, "linkedin", "Kennis"), (11, "linkedin", "Case")]))),
          dict(t="Reacties en berichten *beantwoord*", x="Een post is pas af als je reageert. De student houdt reacties bij en stuurt kansen naar jou door.",
               b=["Reageren in jouw toon", "Kansen gaan naar jou", "Je netwerk actief houden"],
               v=("inbox", dict(title="LinkedIn-reacties", channels=["linkedin"], msgs=[("in", "RV", "Herkenbaar verhaal. Hoe pakken jullie dat aan?"), ("out", "", "Goede vraag! Ik stuur je een bericht met ons stappenplan."), ("in", "LK", "Mooie case, gefeliciteerd!"), ("out", "", "Dank je wel, we zijn er trots op.")]))),
          dict(t="LinkedIn-advertenties die *bereiken*", x="Optioneel: je posts laten zien aan precies de functies en bedrijven die je zoekt.",
               b=["Doelgroep op functie en branche", "Varianten testen", "Werkt in je eigen advertentieaccount"],
               v=("adpost", dict(img="/assets/img/foto/samen-overleg-800.webp", cta="Download onze gids", btn="Download", meta="Gepromoot"))),
          dict(t="Rapportage die je *snapt*", x="Je ziet wat je posts opleveren en wat de student volgende maand schrijft.",
               b=["Weergaven en interacties", "Beste posts van de maand", "Plan voor de volgende maand"],
               v=("dashboard", dict(title="LinkedIn-rapportage", sub="September · bedrijfspagina",
                                    kpis=[("Weergaven", "24.6", 1, "K", "24,6K", "+21%"), ("Interacties", "1180", 0, "", "1.180", "+18%"),
                                          ("Klikken", "402", 0, "", "402", "+12%"), ("Nieuwe volgers", "156", 0, "", "156", "+9%")],
                                    chart="Weergaven per dag", bars_label="Interacties per soort post",
                                    bars=[("i:file", "Kennis", 39), ("i:star", "Cases", 31), ("i:building", "Nieuws", 18), ("i:users", "Vacatures", 12)])))],
    month_t=MAAND, month_x="Een vast ritme op LinkedIn. Hoeveel posts per maand, staat in je offerte.",
    month=[("calendar", "Contentplan", "Onderwerpen voor de maand."),
           ("pen", "Posts schrijven", "Voor je bedrijfspagina en profiel."),
           ("users", "Netwerk en reacties", "Reageren en kansen doorzetten."),
           ("bar-chart", "Rapport en evaluatie", "Wat werkte, en het plan.")],
    cta_t="Benieuwd wat LinkedIn jou *oplevert?*", cta_x="Vertel wie je wilt bereiken. Je krijgt een voorstel met uren, posts per maand en de student die het oppakt.",
    start_t="Zo start je *met LinkedIn*",
    start=[("Kennismaking", "Je doelen, je doelgroep en je huidige profiel en pagina."),
           ("Toegang regelen", "Een beheerdersrol op je bedrijfspagina. Je deelt geen wachtwoorden."),
           ("Toon vastleggen", "Hoe je klinkt, met voorbeelden."),
           ("Eerste posts", "Jij keurt goed, daarna gaat alles live.")]),
}
