# Vacatures voor studenten. Geen salaris of vaste uren genoemd: uren gaan in overleg, naast je studie.
# spec = de dienstpagina waar de student aan meewerkt (voor het icoon en een link).

VACATURES = [
    dict(slug="seo-student", titel="SEO-student", spec="seo-specialist-inhuren",
         kort="Zoekwoordonderzoek, technische SEO en content die rankt voor mkb-klanten.",
         intro="Vind je het leuk om uit te zoeken waarom de ene website bovenaan staat en de andere niet? Als SEO-student help je mkb-bedrijven beter gevonden te worden in Google, met een senior SEO-specialist die met je meekijkt.",
         taken=["Zoekwoordonderzoek doen en pagina's koppelen aan zoekwoorden", "Technische SEO-checks uitvoeren en verbeteringen doorvoeren",
                "Titels, meta descriptions en teksten optimaliseren", "Contentplannen maken en blogs schrijven",
                "Maandrapportages maken met Google Search Console"],
         vragen=["Je studeert marketing, communicatie of iets vergelijkbaars op HBO- of WO-niveau", "Je schrijft goed Nederlands",
                 "Je bent nieuwsgierig naar hoe Google werkt", "Ervaring met WordPress of Search Console is mooi meegenomen"]),
    dict(slug="social-media-student", titel="Social media-student", spec="social-media-uitbesteden",
         kort="Content maken, plannen en community beheren voor mkb-merken.",
         intro="Weet je precies wat werkt op Instagram, LinkedIn en TikTok? Als social media-student maak en plan je content voor mkb-merken en reageer je op hun volgers, begeleid door een senior content- en brandingspecialist.",
         taken=["Contentkalenders maken per klant en per kanaal", "Posts, reels en stories maken en inplannen",
                "Reacties en berichten beantwoorden in de toon van het merk", "Social ads opzetten en bijsturen in Meta en LinkedIn",
                "Maandelijks rapporteren over bereik en interacties"],
         vragen=["Je studeert marketing, communicatie of iets vergelijkbaars op HBO- of WO-niveau", "Je volgt trends op social media op de voet",
                 "Je kunt snel schakelen tussen verschillende merken en tonen", "Ervaring met Meta Business Suite of Canva is mooi meegenomen"]),
    dict(slug="video-editor-student", titel="Video-editor (student)", spec="foto-en-video-laten-maken",
         kort="Filmen en monteren in Premiere Pro, After Effects of DaVinci Resolve.",
         intro="Zit je het liefst achter je montageprogramma? Als video-editor maak je reels, bedrijfsvideo's en advertenties voor mkb-klanten, van opname tot montage.",
         taken=["Video's monteren met ondertiteling, muziek en huisstijl", "Motion graphics en animaties maken",
                "Kleurcorrectie en color grading", "Op locatie filmen en fotograferen", "Versies maken voor elk kanaal en formaat"],
         vragen=["Je studeert (audio)visuele media, communicatie of iets vergelijkbaars op HBO- of WO-niveau",
                 "Je werkt vlot in Premiere Pro, After Effects of DaVinci Resolve", "Je hebt een portfolio of showreel", "Je hebt oog voor ritme en detail"]),
    dict(slug="google-ads-student", titel="Google Ads-student", spec="google-ads-specialist-inhuren",
         kort="Campagnes opzetten, meten en bijsturen voor mkb-klanten.",
         intro="Houd je van cijfers en wil je zien wat een klik oplevert? Als Google Ads-student zet je campagnes op en stuur je ze elke week bij, met een senior SEA-specialist die met je meekijkt.",
         taken=["Zoekwoorden kiezen en campagnes opzetten", "Advertentieteksten schrijven en testen",
                "Conversiemeting inrichten met Google Tag Manager", "Biedingen en budgetten bijsturen", "Resultaten rapporteren in heldere taal"],
         vragen=["Je studeert marketing, bedrijfskunde of iets vergelijkbaars op HBO- of WO-niveau", "Je werkt graag met cijfers en Excel of Google Sheets",
                 "Je bent nauwkeurig", "Een Google Ads-certificaat is mooi meegenomen"]),
    dict(slug="wordpress-student", titel="WordPress-student", spec="wordpress-specialist-inhuren",
         kort="Pagina's bouwen, websites onderhouden en sneller maken.",
         intro="Bouw je graag websites? Als WordPress-student bouw je pagina's, houd je websites bij en maak je ze sneller, voor mkb-klanten met een senior die je werk controleert.",
         taken=["Pagina's bouwen in bestaande thema's en pagebuilders", "Updates, back-ups en beveiliging bijhouden",
                "Websites sneller maken", "De SEO-basis op orde brengen", "WooCommerce-webshops bijhouden"],
         vragen=["Je studeert communicatie en multimedia design, ICT of iets vergelijkbaars op HBO- of WO-niveau", "Je hebt ervaring met WordPress",
                 "Basiskennis van HTML en CSS", "Je lost problemen graag zelf op"]),
    dict(slug="ai-student", titel="AI-student", spec="ai-specialist-inhuren",
         kort="AI-tools en workflows inzetten in de marketing van mkb-bedrijven.",
         intro="Werk je dagelijks met ChatGPT of Claude en zie je overal kansen? Als AI-student help je mkb-bedrijven tijd te besparen met AI, met duidelijke afspraken over privacy en kwaliteit.",
         taken=["Uitzoeken waar AI tijd bespaart in de marketing van een klant", "Assistenten en vaste prompts inrichten",
                "Workflows bouwen met Zapier of Make", "Teams uitleggen hoe ze met AI werken", "Afspraken over data en controle vastleggen"],
         vragen=["Je studeert marketing, informatica of iets vergelijkbaars op HBO- of WO-niveau", "Je werkt vlot met ChatGPT, Claude of Gemini",
                 "Je legt technische dingen helder uit", "Ervaring met Zapier of Make is mooi meegenomen"]),
]

BIEDEN = ["Werk voor echte mkb-klanten, geen oefenopdrachten", "Een ervaren marketeer die je begeleidt en feedback geeft",
          "Uren in overleg, naast je studie", "Remote, of hybride vanuit Den Haag of Mijdrecht", "Je leert de tools die marketeers dagelijks gebruiken"]
